### ISSUE TITLE
question about deploying websockets

### ISSUE THREAD

**Issue by sambrenner** [s4y/space#23]
hey sidney, thanks for all your amazing work on this!

i'm trying to deploy my own space server and i'm running into an issue with the websocket connection. it's trying to connect on two endpoints (`/.reserve/ws` and `/ws`) and failing both times. curious if you have any thoughts?

```
reserve.js:124 WebSocket connection to 'wss://party.samjbrenner.com/.reserve/ws' failed: Error during WebSocket handshake: Unexpected response code: 400
connect @ reserve.js:124
ws.html:28 WebSocket connection to 'wss://party.samjbrenner.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 400
```

my server is running at https://party.samjbrenner.com if you want to take a look. thanks so much!

**Comment by s4y** [comment]
Hey Sam, thanks for trying it!

It looks like you have your instance behind nginx. That's also how I use it, but I had to add a few bits to the reverse proxy config to make WebSockets work. Mine looks like this:

```
	location / {
	 	proxy_pass http://127.0.0.1:8031;

	 	proxy_http_version 1.1;
	 	proxy_set_header Upgrade $http_upgrade;
	 	proxy_set_header Connection "Upgrade";
	 	proxy_set_header        X-Forwarded-For   $remote_addr;
	 	proxy_set_header        X-Real-IP         $remote_addr;
	 	proxy_set_header        Host              $host;
	 	proxy_read_timeout 900;
	 }
```

Not strictly related to your problem, but I also eventually had to bump up a different nginx parameter to handle larger numbers of people, so this might be worth doing at the same time:

```
events {
	worker_connections 20000;
}
```

Some of this info is also available here: https://github.com/s4y/space/wiki/Hosting-a-space

Let me know if that helps, or if things are already set up that way and something else is going on.

**Comment by sambrenner** [comment]
awesome, that fixed the socket problem! there are some other issues now but that's probably from changes 
I made.

I didn't see the wiki, sorry. I'll open a PR to add it to the homepage so people don't miss it in the future.

**Comment by s4y** [comment]
Much appreciated. Let me know if you run/ran into any other issues.
